import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layouts/Navigation";
import Footer from "@/components/layouts/Footer";
import Breadscrumb from "@/components/layouts/Breadscrumb";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className} max-w-screen-desktop mx-auto`}
    >
      <body>
        <NavigationBar />
        <Breadscrumb />
        {children}
        <Footer />
      </body>
    </html>
  );
}
