import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationBar from "@/components/layouts/Navigation";
import Footer from "@/components/layouts/Footer";
import Breadcrumb from "@/components/layouts/Breadcrumb";
import { AuthProvider } from "@/contexts/AuthContext";
import { CategoryProvider } from "@/contexts/CategoryContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html
        lang="en"
        className={`${inter.className} max-w-screen-desktop mx-auto`}
      >
        <body>
          <CategoryProvider>
            <NavigationBar />
            <Breadcrumb />
            {children}
            <Footer />
          </CategoryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
