name: CI/CD Pipeline

on:
  # Triggers the workflow on pull request event for the "main" branch.
  pull_request:
    branches: ["main"]

  workflow_dispatch:

# Defines the jobs to be run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Chekcs-out the repository under our Github Workspace to allow our jobs to access it.

      - uses: actions/setup-node@v2 # Sets up a Node.js environment for the job.
        with:
          node-version: "18"

      # Ensure `package.json` has matching commands under the `run` keys.
      # Installs dependencies defined in package.json
      - name: Install dependencies
        run: npm install

      # Executes the lint script defined in package.json
      - name: Run ESLint
        run: npm run lint

      # Checks all files compliance with Prettier formatting
      - name: Run Prettier Check
        id: prettier_check
        continue-on-error: true
        run: npm run prettier-check

      # Conditional step that fixes formatting if the Prettier check fails
      - name: Fix Prettier Issues
        id: prettier_fix
        if: steps.prettier_check.outcome == 'failure'
        run: npm run prettier-fix

      # Conditional step that looks for changes to decide whether it should commit changes or not
      - name: Commit Prettier Fixes (if any)
        if: steps.prettier_fix.outcome == 'success'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit --message "Fix formatting with Prettier"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi

      # Builds the project to catch build errors, replicate production environment, and ensuring project builds successfully.
      - name: Build the project
        run: npm run build
